version: "2"

services:
  backend:
    build: ./
    container_name: mushub_container
    working_dir: /musician_hub
    restart: always
    command:
      - ./commands/start_server_${MODE}.sh
    ports:
      - ${LOCAL_PORT}:${WSGI_PORT}
    volumes:
      - ./src:/musician_hub/src
      - ./commands:/musician_hub/commands
      - static_content:/musician_hub/src/static
      - media_content:/musician_hub/src/media
    entrypoint: ["/bin/bash", "./commands/start_server_${MODE}.sh"]
    env_file:
      - .env
    depends_on:
      - postgres

  postgres:
    image: postgres:12
    ports:
      - 5432:5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env
    ports:
      - "5000:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  mongodb:
    image: mongo:3-stretch
    ports:
      - 27017:27017
    container_name: mongo_db_container
    command: ["--bind_ip_all", "--smallfiles"]
    volumes:
      - mongo_data:/data/db
    restart: always
    env_file:
      - .env

  mongoadmin:
    image: mongo-express
    restart: always
    container_name: mongo_admin_container
    ports:
      - 8091:8081
    env_file:
      - .env
    links:
      - mongodb
    depends_on:
      - mongodb

  nginx:
    image: nginx:1.19
    volumes:
      - static_content:/musician_hub/src/static
      - media_content:/musician_hub/src/media
      - ./nginx:/etc/nginx/conf.d
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    depends_on:
      - backend

  redis:
    image: redis
    env_file:
      - .env
    restart: on-failure
    depends_on:
      - backend

  celery:
    build: ./
    command:
      - ./commands/start_celery.sh
    restart: always
    volumes:
      - ./src:/musician_hub/src
      - ./commands:/musician_hub/commands
    env_file:
      - .env
    depends_on:
      - redis
      - backend

  celerybeat:
    build: ./
    env_file:
      - .env
    container_name: celerybeat
    command:
      - ./commands/start_celerybeat.sh
    restart: on-failure
    volumes:
      - ./src:/musician_hub/src
      - ./commands:/musician_hub/commands
    depends_on:
      - redis
      - celery

  flower:
    build: ./
    env_file:
      - .env
    command:
      - ./commands/start_flower.sh
    ports:
      - 5555:5555
    volumes:
      - ./src:/musician_hub/src
      - ./commands:/musician_hub/commands
    depends_on:
      - celery
      - redis

  redisadmin:
    container_name: redisadmin
    image: rediscommander/redis-commander:latest
    hostname: redisadmin
    restart: always
    ports:
      - "8092:8081"
    env_file:
      - .env


volumes:
  pg_data: { }
  pgadmin_data: { }
  mongo_data: { }
  static_content: { }
  media_content: { }
