# Generated by Django 3.2.13 on 2022-06-27 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="forumcomments",
            options={"ordering": ["-create_datetime"]},
        ),
    ]
