# Generated by Django 3.2.13 on 2022-08-03 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumposted',
            name='video',
            field=models.URLField(blank=True, db_index=True, max_length=128),
        ),
    ]
